vich_uploader:
    db_driver: orm
    mappings:
        show_poster_images:
            uri_prefix: /img/show_posters
            upload_destination: '%kernel.project_dir%/public/img/show_posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true